### PR TITLE
Update to pyinaturalist 0.11

### PR DESCRIPTION
**Pull request by JWCook**
A new version of pyinaturalist has been released, so here are a few minor changes if you would like to use the latest version. This doesn't have much impact on the features that vespa-watch is using, except for some simplified usage for `create_observation()` and a few other functions. There is also a [dry-run mode](https://pyinaturalist.readthedocs.io/en/stable/general_usage.html#dry-run-mode) and some other features that you may find useful for testing & debugging. I also bumped `requests` to the latest version (2.24.0).

### CODE REVIEW

**Comment by JWCook** [comment]
Actually, there may not be a reason to update pyinaturalist unless there's a specific new feature you want to use. I'm going to close this for now, but feel free to ping me if you could use help with this at some point.

**Comment by niconoe** [comment]
Thanks @JWCook,

Sorry, I missed this PR! Thanks for the work.

I'll consider merging it when working again on Vespa-Watch, we should happen soon. I'm a bit conflicted because on one hand, I prefer to stay up-to-date (and the fact that you're the author gave me confidence), but on the other the Vespa-Watch / iNaturalist sync script is a central (but fragile and not formally tested) piece of code, so I generally touch it as little as possible.

Thanks anyway, I'll absolutely consider merging it!

**Comment by JWCook** [comment]
@niconoe Just curious, since this is sending API requests server-side, do you ever run into rate limiting issues? Just asking because that's a feature that will be in 0.13.

A few months ago I spent some time researching request rate-limiting options, and found that the [leaky bucket algorithm](https://en.wikipedia.org/wiki/Leaky_bucket) is probably the best solution. There wasn't an existing library that did exactly what I wanted, so I picked [pyrate-limiter](https://github.com/vutran1710/PyrateLimiter) and made some updates to it. It's currently being used in the pyinaturalist dev branch, and it works great. That may or may not be relevant to vespa-watch, but thought it might be worth mentioning.

**Comment by peterdesmet** [comment]
Closing PR as Vespa-Watch is currently not interacting directly with iNaturalist anymore.

**Pull request closed without merging**
