### PR TITLE
#306: basic legend for homepage map.

### PR DESCRIPTION
**Pull request by niconoe**

### CODE REVIEW

**Comment by peterdesmet** [comment]
Hi Nico, seems like https://github.com/inbo/vespa-watch/pull/309/files#diff-b4e6714c3f8fe18188f8a5c45ea85d95 contains duplicate entries now. I get:

```
CommandError: Execution of msgfmt failed: /Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:113: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:49: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:117: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:53: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:121: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:57: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:125: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:61: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:129: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:65: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:133: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:69: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:137: dubbele definitie van een bericht...
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:73: ...dit is de plek van de eerste definitie
/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/locale/nl/LC_MESSAGES/djangojs.po:141: dubbele definitie van een bericht...
```

Can you correct this?

**Comment by peterdesmet** [comment]
Update: I have removed the duplicate entries in djangojs.

**Comment by peterdesmet** [comment]
I've updated the legend, so rather than a div above the map using static images, it is now a div _in_ the map, using svg circles, pulling the colors from the config file:

Screenshot 2019-06-24 at 17 40 02

This is all done in vespawatch.js. Static images and code for adding static files to vespawatch.js have been removed. @niconoe can you review this?

**Comment by niconoe** [comment]
Indeed a better approach, and works perfectly for me.

**Pull request merged**
