### PR TITLE
Static s3

### PR DESCRIPTION
**Pull request by stijnvanhoey**
This PR tackles https://github.com/inbo/vespa-watch/issues/241 to make sure the static files are stored on S3 as well (as was already done with the media files). 

To make sure the current structure of the S3 Bucket (all media files start by the `media` key) is kept and uploads of users are separated from the static files (users should not be able to overwrite the static files by upload!), I added two custom classes that provide a different key/path-name (starting with `media` and `static` respectively). 

The feature was tested succesfully on DEV:
- files are provided from S3
image
- creating a new observation stores the uploaded picture in the correct subfolder and the photo is shown correctly in the thumbnail

I deployed it to UAT as well, so please have a check on https://uat.vespawatch.be/ to verify the proper behaviour (although I do not know the effect of the current RP issues on this, @berthuygens ?)

### CODE REVIEW

**Comment by bartaelterman** [comment]
@stijnvanhoey I get a 504 Gateway Timeout at UAT.

**Comment by stijnvanhoey** [comment]
Yup, seems to be the network settings as well on which I do not have any control, will be further checked by @berthuygens.

**Comment by peterdesmet** [comment]
Gateway timeout finally resolved. @stijnvanhoey Separating media from static is a good idea. 👍 Checked one of the URLs on UAT, looks good to me.

**Comment by peterdesmet** [comment]
Would merge this into master, and redeploy on production (will also solve the outstanding 243)

**Pull request merged**
