### PR TITLE
New sync

### PR DESCRIPTION
**Pull request by bartaelterman**
We're implementing a new management command: `inaturalist_sync` which will push and pull to/from iNaturalist in a single command.
Currently only the `push` logic is implemented (push creates and push deletes).
Nevertheless you can merge this pull request to have a working push functionality.

### CODE REVIEW

**Comment by bartaelterman** [comment]
I've implemented the pull. Quite some scenarios are covered by a unit test now. Some extensive testing is still required though.
@peterdesmet @stijnvanhoey  I think it's possible to test on your side now. The flagging mechanism seems to work in the unit tests. However I've been going fast so apologies if I missed something obvious. Next week I will:
- test
- document the process
- clean up TODOs in comments and dead code from the previous sync

**Comment by peterdesmet** [comment]
@bartaelterman i'm not sure where or how to test exactly, so will wait until you pick this up again this week.

**Comment by bartaelterman** [comment]
@peterdesmet as discussed: taxon filter is removed. This branch is ready for testing with real iNaturalist sync.

**Comment by peterdesmet** [comment]
@bartaelterman. Testing this and got:

```
python manage.py inaturalist_sync

1. Delete the nests and individuals that are deleted in VW
Deleting iNaturalist observation #22366812...Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/vespawatch/management/commands/inaturalist_sync.py", line 108, in handle
    self.push_deletes(token)
  File "/Users/peter_desmet/Coding/Repositories/inbo/vespa-watch/vespawatch/management/commands/inaturalist_sync.py", line 28, in push_deletes
    delete_observation(observation_id=obs.inaturalist_id, access_token=access_token)
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/pyinaturalist/rest_api.py", line 209, in delete_observation
    response.raise_for_status()
  File "/Users/peter_desmet/Coding/miniconda3/envs/vespawatch/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.inaturalist.org/observations/22366812.json
```

**Comment by niconoe** [comment]
@peterdesmet: did you started with a fresh local DB in terms of observations? It look like its trying to delete something that was already removed at iNaturalist (maybe from a previous sync version, or manually because it was a quick and dirty test observation)?

@bartaelterman : if that's what's happening, we should probably fix the code so this error is properly logged, but doesn't break/interrupt the synchronisation process (in development this is a relatively normal thing, and in production it should be reported but we should avoid making a "half-sync")

**Comment by dnm-profiling** [comment]
Indeed. Maybe let pyinaturalist raise a `ObservationNotFound` exception and catch that in the vespawatch code?

**Comment by bartaelterman** [comment]
Indeed. Maybe let pyinaturalist raise a ObservationNotFound exception and catch that in the vespawatch code?

**Comment by peterdesmet** [comment]
Not a fresh local DB, no. On production it won't be fresh DB either. According to our sync doc a record removed at iNat should be deleted in VespaWatch.

**Comment by bartaelterman** [comment]
@peterdesmet fix pushed. Beware: requirements are updated so make sure to update your environment

**Comment by peterdesmet** [comment]
@bartaelterman, remaining issues still:

- Indiv: description is not updated
- Nest: description is not updated

**Comment by peterdesmet** [comment]
I will create separate issues.

**Comment by peterdesmet** [comment]
Merging this for launch. Remaining issues can be fixed later.

**Pull request merged**
