### PR TITLE
Vue fields styling

### PR DESCRIPTION
**Pull request by niconoe**
There's now a basic mechanism in place that allows styling a Vue.js based field to report validation errors from a (Django) form.

It currently sets a red border when observation time, latitude or longitude is missing.

Don't hesitate to test, extend/improve and merge.

### CODE REVIEW

**Comment by bartaelterman** [comment]
Hi @niconoe ,

I'm looking at these fields. I think we still miss the address field for nests and the the terms of service checkbox in both cases.

I also added a commit to also display the error message below the field

**Comment by bartaelterman** [comment]
note to self, I hard coded the error message in there. Should make it a prop and let django insert the right message in the component

**Comment by bartaelterman** [comment]
@niconoe  I fixed the address field for the nest form. For adding the error message dynamically though, I'll need your help. I can't seem to find how to get the error message(s) of the field (without html tags) to add them as properties to the vuejs components.

**Comment by niconoe** [comment]
@bartaelterman : no problem, I'll investigate that soon!

**Comment by bartaelterman** [comment]
@niconoe  I found a way to add the messages dynamically. Seems to work for me on both nests and individuals, in english and dutch. Does it look ok for you?

**Comment by bartaelterman** [comment]
@peterdesmet for some reason I cannot ask Nico "officially" to review this PR.
@niconoe can you have a look at my changes?

**Comment by bartaelterman** [comment]
I'm going to merge this anyway to continue progress on #297. This is holding me back otherwise

**Comment by peterdesmet** [comment]
Looks good!

**Pull request merged**
