### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by stijnvanhoey**
Includes the files/configurations for the current DEV deployment. Adapted to and tested with latest repo structure.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@niconoe can I merge?

**Comment by niconoe** [comment]
Sure, I don't think it interferes with the rest (and anyway it's still a good time to break things!)

**Comment by bartaelterman** [comment]
@stijnvanhoey can you remove the inat app id from the settings and put it in an environment variable or something like that?

**Comment by bartaelterman** [comment]
Ah, although it's only the app id... That doesn't allow you to log in right @niconoe ? In that case it's ok

**Comment by stijnvanhoey** [comment]
I thought this was ok to share, but I can adapt the setup if not, just let me know

**Comment by stijnvanhoey** [comment]
@niconoe can you verify and let me know if I should hide the inat app id or not?

**Comment by niconoe** [comment]
I can't find the info in the API documentation. To me (according to experience with similar APIs), app_id should be public information, while app_secret should be kept... secret.

Just to be safe, I'll double check with the iNaturalist developers and let you know!

**Pull request merged**
